// Integração REST com Supabase Auth e Postgres. Apenas chave publicável no navegador.
const Cloud=(()=>{let session=null,refreshing=null;const key='aureon-session-v1';const config=()=>window.AUREON_CONFIG||{};const blank=()=>({transactions:[],goals:[],accounts:[{id:'principal',name:'Principal',initial:0}],budgets:{},settings:{theme:'dark',focus:false,reminders:true},chat:[]});
function configured(){const c=config();return c.url.startsWith('https://')&&!!c.key}
function store(s){session=s;if(s)sessionStorage.setItem(key,JSON.stringify(s));else sessionStorage.removeItem(key)}
function error(message,status){const e=Error(message);e.status=status;return e}
async function request(path,method='GET',body,token){const c=config();let r;try{r=await fetch(c.url+path,{method,headers:{apikey:c.key,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined})}catch{throw error('Não foi possível conectar. Confira sua internet e a configuração do site.',503)}let data;try{data=await r.json()}catch{data={}}if(!r.ok){let msg=data.msg||data.error_description||data.message||data.error||'Não foi possível concluir.';if(msg==='Invalid login credentials')msg='E-mail ou senha incorretos.';if(msg==='Email not confirmed')msg='Confirme seu e-mail antes de entrar.';if(r.status===429)msg='Muitas tentativas. Aguarde um pouco e tente novamente.';throw error(msg,r.status)}return data}
async function token(){if(!session)throw error('Entre na sua conta.',401);if(!session.expires_at||session.expires_at<Date.now()/1000+60){if(!refreshing)refreshing=request('/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:session.refresh_token}).then(s=>{store({...s,expires_at:Date.now()/1000+s.expires_in});return s.access_token}).catch(e=>{if(e.status===400||e.status===401)store(null);throw e}).finally(()=>refreshing=null);return refreshing}return session.access_token}
async function initialize(){try{session=JSON.parse(sessionStorage.getItem(key)||'null')}catch{session=null}const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('error_description')){const msg=hash.get('error_description');history.replaceState(null,'',location.pathname);throw error(msg,400)}if(hash.has('access_token')){store({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_at:Date.now()/1000+Number(hash.get('expires_in')||3600)});Cloud.recovery=hash.get('type')==='recovery';history.replaceState(null,'',location.pathname+location.search)}}
async function api(path,method='GET',data){if(path==='/api/register'||path==='/api/login'){const isSignup=path==='/api/register';const route=isSignup?'/auth/v1/signup?redirect_to='+encodeURIComponent(location.origin+'/'):'/auth/v1/token?grant_type=password';const out=await request(route,'POST',{email:data.email,password:data.password,...(isSignup?{data:{name:data.name}}:{})});if(!out.access_token)return {confirm:true};store({...out,expires_at:Date.now()/1000+out.expires_in});return {ok:true}}
if(path==='/api/logout'){try{if(session)await request('/auth/v1/logout','POST',{},await token())}finally{store(null)}return {ok:true}}
const access=await token();if(method==='GET'){const u=await request('/auth/v1/user','GET',undefined,access);const result=await request('/rest/v1/rpc/get_aureon','POST',{},access);const row=Array.isArray(result)?result[0]:result;if(!row)throw error('Execute a configuração do banco no Supabase.',503);return {user:{name:row.name,email:u.email},state:row.state,version:row.version}}
if(method==='PUT'){const result=await request('/rest/v1/rpc/save_aureon','POST',{new_name:data.name,new_state:data.state,expected_version:data.version},access);if(result===null||result===undefined)throw error('Os dados mudaram em outra aba. Atualize a página e tente novamente.',409);return {ok:true,version:result}}
throw error('Ação não reconhecida.',400)}
async function recover(email){return request('/auth/v1/recover?redirect_to='+encodeURIComponent(location.origin+'/'),'POST',{email})}
async function reset(password){return request('/auth/v1/user','PUT',{password},await token())}
return {configured,initialize,api,recover,reset,version:0,recovery:false,blank};})();
